# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Minahan - Software Engineer
description: > # this means to ignore newlines until "baseurl:"
  John Minahan Portfolio Site
baseurl: /home  # the subpath of your site, e.g. /blog
url: https://jminahan.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: John Minahan
email: jminahan.cs@gmail.com

navigation:
  - text: Home
    url: /
    out: false
  - text: Resume (Web)
    url: /resume.html
    out: false
  - text: Resume (PDF)
    url: /resume.pdf
    out: false
  - text: Github
    url: https://github.com/jminahan
    out: true
  - text: Discussion Posts
    url: /dispage.html
    out: false
  - text: LinkedIn
    url: https://www.linkedin.com/in/john-minahan-557768144/
    out: true

projects:

social:

# Plugins
gems:
  - jekyll-seo-tag
